### ISSUE TITLE
[Android Bootcamp]:Project1-Instagram Client - ready for review

### ISSUE THREAD

**Issue by rehan-0601** [rehan-0601/InstagramClient#1]
My app is complete, please review. /cc @codepathreview @codepath

Questions:
1.I could'nt get my font color/sizes to look like instagram. How do you find out the fonts/styles they use and use the same typeface.(android gave me only 4 typefaces, how do you import more fonts)
2.The REST end point for /media/popular seems to be returning a max of 8 comments.(Though the count is > 8). Im i messing up or is this expected behavior.
3.For an imageView does it matter if i use padding or layout margin.(sorry if i do'nt have the box model right.)

**Comment by codepathreview** [comment]
Decent work, Rehan. 

Regarding your questions:
1. You can use a chrome plugin called "ColorPick Eyedropper" for finding color values. Checkout http://stackoverflow.com/questions/3424165/can-i-embed-a-custom-font-in-an-android-application to understand how to import custom fonts.
2. Checkout https://instagram.com/developer/endpoints/comments/ to understand how to get comments for a photo.
3. Checkout http://stackoverflow.com/questions/4619899/difference-between-a-views-padding-and-margin to understand the difference between margin and padding.

A few notes after checking out the code:
- Good layout, proper view naming, usage of sp/dp, margin and relative placement rules
- Correct use of Styles, Colors and String resources
- Nice to see you used the SwipeRefreshLayout for easy stream refreshes
- Good job using the ViewHolder pattern to improve performance of photos ListView.
- Good to see that you used a dialog instead of activity to show all comments.
- Consider polishing UI little more. 
- Consider adding profile pic along with comments in "all comments" view
- Consider including a check to see if internet is available to detect any network failures. Show an appropriate message in case of failure.
- Consider overriding onFailure method in JsonHttpResponseHandler to handle error messages appropriately.

One of the most important part of these projects is that you add additional features and tweak the UI / UX because that will provide many more learning opportunities. I would encourage you to complete the projects each week with required stories early and then spend time adding your own UI elements and experimenting with optional extensions that will improve the user experience.

We have provided a detailed Project 1 Feedback Guide here which covers the most common points we see for this project. Read through the feedback guide point-by-point to determine other ways you could improve your submission. You should consider going back and implementing applicable feedback as well. Keep in mind that one of the most important parts of Android development is learning the correct patterns and conventions.

Hopefully this first project has given you a better sense of working with RelativeLayout which is a very flexible layout system, probably one of the most powerful responsive-first layout systems available across web and mobile platforms. This assignment also gave us our first introduction to networking, working with APIs and loading remote images. The next assignment will introduce new concept such as accepting user input and navigating between activities but will also reinforce important concepts such as networking, using APIs, handling remote images.

If you have any particular questions about the assignment in general or on any of the feedback, feel free to reply here or or email us support@codepath.com.

P.S. Good to see you properly added the readme with features and screenshots to your project as described in the submitting assignments guide!
